replicaCount: 1
image:
  repository: accounts-service
  tag: "0.0.1-SNAPSHOT"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8081
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
