apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.2.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: dashboard-business
              mountPath: /var/lib/grafana/dashboards/business-metrics.json
              subPath: business-metrics.json
            - name: dashboard-http
              mountPath: /var/lib/grafana/dashboards/http-metrics.json
              subPath: http-metrics.json
            - name: dashboard-jvm
              mountPath: /var/lib/grafana/dashboards/jvm-metrics.json
              subPath: jvm-metrics.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-provider
          configMap:
            name: grafana-dashboards-provider
        - name: dashboard-business
          configMap:
            name: grafana-dashboard-business
        - name: dashboard-http
          configMap:
            name: grafana-dashboard-http
        - name: dashboard-jvm
          configMap:
            name: grafana-dashboard-jvm
