server:
  port: 9000

spring:
  application:
    name: auth-server

security:
  jwt:
    key-id: ${JWT_KEY_ID:my-bank-app-rsa-key-2024}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
