apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/bankdb?currentSchema=accounts"
  OAUTH2_ISSUER_URI: "http://auth-server:9000"
  OAUTH2_TOKEN_URI: "http://auth-server:9000/oauth2/token"
  OAUTH2_CLIENT_ID: "accounts-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ZIPKIN_BASE_URL: "http://zipkin:9411"
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5044"
