apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "bankuser"
  SPRING_DATASOURCE_PASSWORD: "bankpassword"
