server:
  port: 8084

spring:
  application:
    name: notifications-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb?currentSchema=notifications}
    username: ${SPRING_DATASOURCE_USERNAME:bankuser}
    password: ${SPRING_DATASOURCE_PASSWORD:bankpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:9000}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
