apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  JWT_KEY_ID: "my-bank-app-rsa-key-2024"
  ZIPKIN_BASE_URL: "http://zipkin:9411"
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5044"
