server:
  port: 8080

spring:
  application:
    name: front-app
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      client:
        registration:
          front-app:
            client-id: front-app
            client-secret: front-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/front-app
            scope: openid,profile,ACCOUNTS_READ,ACCOUNTS_WRITE,CASH_WRITE,TRANSFER_WRITE
        provider:
          front-app:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-name-attribute: sub

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

gateway:
  url: http://localhost:8765
