input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}"
    topics => ["bank-logs"]
    codec => json
    group_id => "logstash-logs-consumer"
    auto_offset_reset => "earliest"
    consumer_threads => 1
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "bank-logs-%{+YYYY.MM.dd}" }
  }

  # Маскируем чувствительные данные
  mutate {
    gsub => [
      "message", "password=[^,&\s]+", "password=***",
      "message", "secret=[^,&\s]+", "secret=***"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
