input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "bank-logs-%{+YYYY.MM.dd}" }
  }

  # Маскируем чувствительные данные
  mutate {
    gsub => [
      "message", "password=[^,&\s]+", "password=***",
      "message", "secret=[^,&\s]+", "secret=***"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
