server:
  port: 8084

spring:
  application:
    name: notifications-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb?currentSchema=notifications
    username: bankuser
    password: bankpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notifications
