server:
  port: 8083

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb?currentSchema=transfer
    username: bankuser
    password: bankpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: transfer
